### ISSUE TITLE
Same as basu?

### ISSUE THREAD

**Issue by OutOfContainment** [chimera-linux/tangle#2]
It seems like this project is trying to do the same thing as https://git.sr.ht/~emersion/basu library; 
this adds unnecessary complexity for package maintainers and almost everyone else who ports sd-bus.

I kindly ask you not to make headache for all of us. Same codebase in two different projects seems utterly wasteful.

Basu is already a package for Alpine, ALT, Void, Gentoo, Guix and FreeBSD ports.

**Comment by q66** [comment]
besides being severely outdated (and upstream confirming they have no plans to do anything much with it), basu does not integrate sd-event and rips out all the internal event loop stuff so it cannot be integrated with an external port of sd-event (it does not have apis such as `sd_bus_attach_event`), so i'm afraid that's not happening

**Comment by OutOfContainment** [comment]
This is understandable; though I don't see much reason for it to be updated.

Considering this, I have 2 questions:

1. Is there a sd-bus dependent software that works with tangle but does not work with basu?
2. If what you said is true, have you considered a possibility for chimera to take over basu maintenance?

**Comment by q66** [comment]
1. not yet - well there may be but unknown because i have not tested any (but there will be: chimera's port of dbus-broker will use it)
2. it's way more work to update basu and/or reintegrate the extra event stuff than to make a fresh port, so i made a fresh port; tangle is not missing anything basu has, so anything that wants to can just switch (it's also fairly easy to build anything using basu against tangle); i don't really feel like going through the effort of taking over basu, got plenty of other things to worry about

in any case this is here to stay
